---
title: "git_01"
author: "Jeannet Cendejas"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Learn well your grammar,  
And never stammar,  
Write well and neatly,  
And sing most sweetly,  
Be enterprising,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I have been one acquainted with the night.  
I have walked out in rain—and back in rain.  
I have outwalked the furthest city light.  
I have looked down the saddest city lane.  
I have passed by the watchman on his beat.  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
If ever two were one, then surely we.  
If ever man were loved by wife, then thee.  
If ever wife was happy in a man,  
Compare with me, ye women, if you can.  
I prize thy love more than whole mines of gold,  
Or all the riches that the East doth hold.  
My love is such that rivers cannot quench,  
Nor ought but love from thee give recompense.  
Thy love is such I can no way repay;  
The heavens reward thee manifold, I pray.  
Then while we live, in love let’s so persever,  
That when we live no more, we may live ever.  
  